/** Tradução de tags OSM para rótulos em português. */
const BUILDING: Record<string, string> = {
  yes: 'Edificação',
  house: 'Casa',
  residential: 'Residencial',
  apartments: 'Prédio residencial',
  detached: 'Casa',
  terrace: 'Casas geminadas',
  semidetached_house: 'Casa geminada',
  commercial: 'Comercial',
  retail: 'Comércio',
  office: 'Escritórios',
  industrial: 'Industrial',
  warehouse: 'Galpão',
  church: 'Igreja',
  cathedral: 'Catedral',
  chapel: 'Capela',
  school: 'Escola',
  university: 'Universidade',
  hospital: 'Hospital',
  public: 'Prédio público',
  civic: 'Prédio público',
  government: 'Governo',
  train_station: 'Estação ferroviária',
  transportation: 'Transporte',
  hotel: 'Hotel',
  supermarket: 'Supermercado',
  garage: 'Garagem',
  garages: 'Garagens',
  shed: 'Depósito',
  roof: 'Cobertura',
  kiosk: 'Quiosque',
  stadium: 'Estádio',
  sports_hall: 'Ginásio',
  sports_centre: 'Centro esportivo',
  bank: 'Banco',
  police: 'Polícia',
  townhall: 'Prefeitura',
  courthouse: 'Fórum',
  place_of_worship: 'Templo',
  pharmacy: 'Farmácia',
  restaurant: 'Restaurante',
  cafe: 'Café',
  fuel: 'Posto de combustível',
  bakery: 'Padaria',
  library: 'Biblioteca',
  cinema: 'Cinema',
  post_office: 'Correios',
  bus_station: 'Rodoviária',
  marketplace: 'Mercado',
  community_centre: 'Centro comunitário',
  social_facility: 'Assistência social',
  fire_station: 'Bombeiros',
  dentist: 'Dentista',
  clinic: 'Clínica',
  doctors: 'Consultório',
  arts_centre: 'Centro cultural',
};

export function buildingLabel(type: string): string {
  return BUILDING[type] ?? type.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}

const POI: Record<string, string> = {
  ...BUILDING,
  fast_food: 'Lanchonete',
  bar: 'Bar',
  pub: 'Bar',
  ice_cream: 'Sorveteria',
  clothes: 'Roupas',
  shoes: 'Calçados',
  mobile_phone: 'Celulares',
  convenience: 'Conveniência',
  hairdresser: 'Cabeleireiro',
  beauty: 'Estética',
  optician: 'Ótica',
  hardware: 'Material de construção',
  furniture: 'Móveis',
  books: 'Livraria',
  greengrocer: 'Hortifrúti',
  butcher: 'Açougue',
  department_store: 'Loja de departamentos',
  variety_store: 'Variedades',
  electronics: 'Eletrônicos',
  chocolate: 'Chocolates',
  computer: 'Informática',
  gift: 'Presentes',
  pet: 'Pet shop',
  veterinary: 'Veterinário',
  atm: 'Caixa eletrônico',
  parking: 'Estacionamento',
  fitness_centre: 'Academia',
  museum: 'Museu',
  attraction: 'Atração turística',
  guest_house: 'Pousada',
  monument: 'Monumento',
  memorial: 'Memorial',
};

export function poiLabel(value: string): string {
  return POI[value] ?? value.replace(/_/g, ' ');
}

export const ZONING: Record<string, string> = {
  residencial: 'Residencial',
  comercial: 'Comercial',
  industrial: 'Industrial',
  misto: 'Uso misto',
  institucional: 'Institucional',
};
